# Generated by Django 6.0.5 on 2026-05-28 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 — Direct'), ('scope2', 'Scope 2 — Electricity'), ('scope3', 'Scope 3 — Value Chain')], max_length=10)),
                ('category', models.CharField(choices=[('stationary_combustion', 'Stationary Combustion'), ('mobile_combustion', 'Mobile Combustion'), ('purchased_electricity', 'Purchased Electricity'), ('business_travel_flight', 'Business Travel — Flight'), ('business_travel_hotel', 'Business Travel — Hotel'), ('business_travel_car', 'Business Travel — Car'), ('purchased_goods', 'Purchased Goods & Services')], max_length=50)),
                ('activity_start', models.DateField()),
                ('activity_end', models.DateField(blank=True, null=True)),
                ('reporting_year', models.IntegerField()),
                ('activity_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('activity_unit', models.CharField(max_length=20)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('source_type', models.CharField(choices=[('sap_fuel_procurement', 'SAP'), ('utility_electricity', 'Utility'), ('travel_corporate', 'Travel'), ('manual', 'Manual Entry')], max_length=50)),
                ('source_row_id', models.CharField(blank=True, max_length=100)),
                ('raw_data_snapshot', models.JSONField(default=dict)),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('flagged', 'Flagged / Suspicious'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit')], default='pending_review', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='ingestion.importbatch')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.tenant')),
            ],
            options={
                'ordering': ['-activity_start'],
            },
        ),
    ]
