# Generated by Django 6.0.5 on 2026-05-28 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel_procurement', 'SAP Fuel & Procurement'), ('utility_electricity', 'Utility Electricity'), ('travel_corporate', 'Corporate Travel')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='imports/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawSAPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('BUKRS', models.CharField(blank=True, max_length=10)),
                ('WERKS', models.CharField(blank=True, max_length=10)),
                ('MATNR', models.CharField(blank=True, max_length=40)),
                ('MENGE', models.CharField(blank=True, max_length=20)),
                ('MEINS', models.CharField(blank=True, max_length=10)),
                ('BLDAT', models.CharField(blank=True, max_length=20)),
                ('WRBTR', models.CharField(blank=True, max_length=20)),
                ('WAERS', models.CharField(blank=True, max_length=5)),
                ('BKTXT', models.CharField(blank=True, max_length=255)),
                ('parse_warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_rows', to='ingestion.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='RawTravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('trip_id', models.CharField(blank=True, max_length=100)),
                ('traveler_id', models.CharField(blank=True, max_length=100)),
                ('segment_type', models.CharField(blank=True, choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('car', 'Car Rental'), ('rail', 'Rail')], max_length=20)),
                ('origin_code', models.CharField(blank=True, max_length=10)),
                ('destination_code', models.CharField(blank=True, max_length=10)),
                ('departure_date', models.CharField(blank=True, max_length=30)),
                ('return_date', models.CharField(blank=True, max_length=30)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('cabin_class', models.CharField(blank=True, max_length=30)),
                ('cost_usd', models.CharField(blank=True, max_length=20)),
                ('nights', models.CharField(blank=True, max_length=10)),
                ('parse_warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_rows', to='ingestion.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='RawUtilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('meter_id', models.CharField(blank=True, max_length=100)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('billing_period_start', models.CharField(blank=True, max_length=30)),
                ('billing_period_end', models.CharField(blank=True, max_length=30)),
                ('consumption_kwh', models.CharField(blank=True, max_length=20)),
                ('demand_kw', models.CharField(blank=True, max_length=20)),
                ('tariff_code', models.CharField(blank=True, max_length=50)),
                ('cost_local_currency', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(blank=True, max_length=5)),
                ('parse_warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_rows', to='ingestion.importbatch')),
            ],
        ),
    ]
